### ISSUE TITLE
KITTI Version

### ISSUE THREAD

**Issue by xuwuzhou** [bzdfzfer/litamin2#1]
Thanks for your open-source work.
I noticed that your paper 《LiTAMIN2: Ultra Light LiDAR-based SLAM using Geometric Approximation applied with KL-Divergence》(ICRA2021) has a great performance on KITTI. But this code version doesn't have any KITTI config.
So, I wonder that when the KITTI version code will be released?

Best wishes.

**Comment by bzdfzfer** [comment]
Hi, this is not my paper. I am trying to implement the scan matching part mentioned in LiTAMIN2. Sadly, the code for KITTI experiments has not been WRITTEN for now. I believe this will be done in the following couple of days.

**Comment by rlabs-oss** [comment]
is it possible to make a command line version to e.g read 10 .pcd files of 12000 points each, and assemble the global map? - Could you point me at the essential parts of the code to realize this?

**Comment by bzdfzfer** [comment]
> is it possible to make a command line version to e.g read 10 .pcd files of 12000 points each, and assemble the global map? - Could you point me at the essential parts of the code to realize this?

sure it works. Just look cpp files at test folder, you can easily load two pcd files to be aligned with command lines. To assemble a global map, current implementation cannot achieve this, since I just tried two scan alignment result. However, you can accumulate them with calculated N-1 global point cloud poses.

**Comment by rlabs-oss** [comment]
after cmake and make it errors with boost related lib problems. make litamin produced the litamin2_align binary which did align two .pcd files and visualize them, thats great, thank you.
