### ISSUE TITLE
about covariance cost function

### ISSUE THREAD

**Issue by FangGet** [bzdfzfer/litamin2#2]
comment https://github.com/bzdfzfer/litamin2/blob/d52e8aa1ac3a296b60d37752e174bf9091881a2c/include/litamin2/impl/litamin2point2voxelnewton_impl.hpp#L339

it seems not necessary.

**Comment by bzdfzfer** [comment]
Hi, thanks a lot for helpping debuging this function! I am struggling for graduating issues recently and have no time to check your problem. Maybe one or two months later I will concentrate to this package again. Sorry for the update delay. Please keep debugging if your are interested!
