### ISSUE TITLE
/usr/local/include/eigen3/Eigen/src/Core/util/XprHelper.h:127: Eigen::internal::variable_if_dynamic<T, Value>::variable_if_dynamic(T) [with T = long int; int Value = 6]: Assertion `v == T(Value)' failed

### ISSUE THREAD

**Issue by PANFEI-CHENG** [bzdfzfer/litamin2#3]
/usr/local/include/eigen3/Eigen/src/Core/util/XprHelper.h:127: Eigen::internal::variable_if_dynamic<T, Value>::variable_if_dynamic(T) [with T = long int; int Value = 6]: Assertion `v == T(Value)' failed
I meet this question when I run "rosrun litamin2 litamin2_align ./src/litamin2/data/251370668.pcd ./src/litamin2/data/251371071.pcd" with ubuntu 16.04andEigen3.3.9.Could you help me?

**Comment by bzdfzfer** [comment]
please provide more details about this bug.

**Comment by PANFEI-CHENG** [comment]
![Uploading IMG20220909143420.jpg…]()
like this. On the Internet, it was said that a higher version of eigen could be replaced, but I tried it, but it didn't work

**Comment by PANFEI-CHENG** [comment]
I solved the problem by reinstalling the system.Thank you.
