### ISSUE TITLE
Running KITTI error "std::bad_alloc"

### ISSUE THREAD

**Issue by AlfredMoore** [bzdfzfer/litamin2#4]
![1afe9c0c747ee4c437fede0c2c31930](https://user-images.githubusercontent.com/113639875/228124517-4515d497-7163-451b-a68d-ee978cb00454.png)
Could someone tell me how to fix this? Is that because insufficient memory allocation ?
BTW, I am using VMware Ubuntu18

**Comment by bzdfzfer** [comment]
pls check your kitti data folder path and obey the directory definition rules as shown in my code.
